export async function getDemoAssetURL(kind: 'pointcloud' | 'splat'): Promise<string> {
  // These assets are generated by the NeRF proxy on startup.
  // pointcloud: /public/assets/demo_cloud.ply
  // splat: we reuse the point cloud as an approximate fallback
  if (kind === 'pointcloud') return '/assets/demo_cloud.ply'
  return '/assets/demo_cloud.ply'
}

