version: "3.9"
services:
  server:
    build:
      context: ./server/nerf-proxy
      dockerfile: Dockerfile
    ports:
      - "7007:7007"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - server

